IBM_STT_API_KEY = "YOUR_KEY_HERE"
IBM_STT_URL = "YOUR_IBM_SPEECH_TO_TEXT_URL"

IBM_TTS_API_KEY = "YOUR_KEY_HERE"
IBM_TTS_URL = "YOUR_IBM_TEXT_TO_SPEECH_URL"

HOUNDIFY_CLIENT_ID = "YOUR_KEY_HERE"
HOUNDIFY_CLIENT_KEY = "YOUR_HOUNDIFY_CLIENT_KEY_HERE"

IBM_ML_API_KEY = "YOUR_IBM_ML_KEY_HERE"
IBM_ML_LOCATION = "YOUR_IBM_ML_LOCATION"
